#!/bin/sh

if [ -f /usr/local/e2/etc/fp/rtc ] ; then
	LIMIT_TIME=1514808000 #01.01.2018
	RTC_TIME=$( cat /usr/local/e2/etc/fp/rtc )
	SYSTEM_TIME=$(date +%s)
	if [ "$RTC_TIME" -gt "$LIMIT_TIME" ]; then
		if [ "$SYSTEM_TIME" -lt "$LIMIT_TIME" ]; then
			date -s @$RTC_TIME
			echo "set rtc time ..."
		fi
	fi
fi

exit 0
