#!/bin/bash

PIDFILE=/var/run/oscam.pid
if (kill -0 `cat $PIDFILE`)
	then
	echo "it's alive!" > /dev/null
	else
	rm $PIDFILE
	sudo softcam start > /dev/null
	echo "OSCAM restarted at `date`" >> /var/log/oscam/oscam-crash.log
fi
